[project]
name = "db"
version = "0.1.0"
dependencies = [
  "django-mongodb-backend",
]

[project.optional-dependencies]
dev = [
  "pre-commit",
]

[tool.setuptools]
packages = ["backend", "mongo_migrations"]
